In [10]:
import numpy as np
import time
from numpy.random import rand

N = 150

matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("파이썬의 기능만으로 계산한 결과: %.2f[sec]" % float(time.time() -start))

start = time.time()

matC = np.dot(matA, matB)

print("NumPy를 사용한 경우의 계산 결과: %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과: 1.81[sec]
NumPy를 사용한 경우의 계산 결과: 0.00[sec]


In [11]:
start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("파이썬의 기능만으로 계산한 결과: %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과: 1.77[sec]


In [12]:
start = time.time()

matC = np.dot(matA, matB)

print("NumPy를 사용한 경우의 계산 결과: %.2f[sec]" % float(time.time() - start))

NumPy를 사용한 경우의 계산 결과: 0.00[sec]


In [14]:
import numpy as np

storages = [24,3,4,23,10,12]
print(storages)

np_storages = np.array(storages)
print(np_storages)

print(type(np_storages))

[24, 3, 4, 23, 10, 12]
[24  3  4 23 10 12]
<class 'numpy.ndarray'>


In [15]:
storages = [1,2,3,4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [17]:
import numpy as np
storages = np.array([1,2,3,4])
storages += storages
print(storages)

[2 4 6 8]


In [21]:
import numpy as np

arr = np.array([2,5,3,4,8])

print('arr+arr')
print(arr+arr)

print('arr-arr')
print(arr-arr)

print('arr**3')
print(arr**3)

print('1/arr')
print(1/arr)

arr+arr
[ 4 10  6  8 16]
arr-arr
[0 0 0 0 0]
arr**3
[  8 125  27  64 512]
1/arr
[0.5        0.2        0.33333333 0.25       0.125     ]


In [23]:
import numpy as np

arr=np.arange(10)
print(arr)

print(arr[3:6])

arr[3:6] =24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [29]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2=arr1
arr2[0] = 100
print(arr2)

print(arr1)


arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 =arr1.copy()
arr2[0] =100
print(arr2)

print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]


In [30]:
arr = np.array([2,4,6,7])
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [33]:
arr = np.array([2,4,6,7])
print(arr[arr % 3 == 1])

[4 7]


In [34]:
# 부울 인덱스
import numpy as np

arr = np.array([2,3,4,5,6,7])

print(arr % 2 == 0)

print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


In [43]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

arr_abs = np.abs(arr)
print(arr_abs)

print(np.exp(arr_abs))  # 거듭제곱
print(np.sqrt(arr_abs)) # 제곱근
print(np.sin(arr_abs))
print(np.cos(arr_abs))
print(np.fix(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]
[-0.7568025   0.41211849 -0.28790332 -0.7568025   0.91294525]
[-0.65364362 -0.91113026 -0.95765948 -0.65364362  0.40808206]
[ 4.  9. 16.  4. 20.]


In [42]:
import numpy as np

arr1 = [2,5,7,9,5,2]
arr2 = [2,5,8,3,1]

# 중복을 제거한 배열을 변수에 대입
new_arr1 = np.unique(arr1)
print(new_arr1)

# 합집합
print(np.union1d(new_arr1, arr2))

#교집합
print(np.intersect1d(new_arr1, arr2))

#차집합
print(np.setdiff1d(new_arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [51]:
# 난수
import numpy as np

from numpy.random import randint

arr1 = randint(0, 11, (5, 2))
print(arr1)

# 변수 arr2에 0 이상 1미만의 난수를 3개 생성
arr2 = np.random.rand(3)
print(arr2)

[[ 4  9]
 [ 0  2]
 [ 6  5]
 [ 4  4]
 [ 1 10]]
[0.02648533 0.2990319  0.25336783]


In [52]:
# 2차원배열

import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

print(arr.shape)

# 변수 arr을 4행 2열의 행렬로 변환
print(arr.reshape(4,2))

arr = np.array([[1,2,3],[4,5,6]])
print(arr[1])

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[4 5 6]
