In [10]:
import numpy as np
import time
from numpy.random import rand

N = 150

matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("파이썬의 기능만으로 계산한 결과: %.2f[sec]" % float(time.time() -start))

start = time.time()

matC = np.dot(matA, matB)

print("NumPy를 사용한 경우의 계산 결과: %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과: 1.81[sec]
NumPy를 사용한 경우의 계산 결과: 0.00[sec]


In [11]:
start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("파이썬의 기능만으로 계산한 결과: %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과: 1.77[sec]


In [12]:
start = time.time()

matC = np.dot(matA, matB)

print("NumPy를 사용한 경우의 계산 결과: %.2f[sec]" % float(time.time() - start))

NumPy를 사용한 경우의 계산 결과: 0.00[sec]


In [52]:
import numpy as np

storages = [24,3,4,23,10,12]
print(storages)

# ndarray 배열을 생성하고 변수 np_storages에 대입하세요
np_storages = np.array(storages)
print(np_storages)

# 변수 np_storages의 자료형을 출력
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
[24  3  4 23 10 12]
<class 'numpy.ndarray'>


In [53]:
# numpy를 사용하지 않고 실행합니다
storages = [1,2,3,4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [54]:
# numpy를 사용하여 실행합니다
import numpy as np
storages = np.array([1,2,3,4])
storages += storages
print(storages)

[2 4 6 8]


In [43]:
# numpy 1차원 배열 계산
import numpy as np

arr = np.array([2,5,3,4,8])

print('arr+arr')
print(arr+arr)

print('arr-arr')
print(arr-arr)

print('arr**3')
print(arr**3)

print('1/arr')
print(1/arr)

arr+arr
[ 4 10  6  8 16]
arr-arr
[0 0 0 0 0]
arr**3
[  8 125  27  64 512]
1/arr
[0.5        0.2        0.33333333 0.25       0.125     ]


In [47]:
# 1차원 ndarray 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
#arr[start:end] = 변경하려는 값, 끝숫자는 end-1까지 주의
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


In [42]:
# 특정부분만 출력 ,특정부분의 값을 변경
import numpy as np

arr=np.arange(10)
print(arr)

# 변수 arr의 요소 중 3,4,5만 출력
print(arr[3:6])

# 변수 arr의 요소 중 3,4,5을 24로 변경하십시오
arr[3:6] =24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [48]:
# ndarray 사용시 주의사항
import numpy as np

# ndarray를 그대로 arr2 변수에 대입한 경우를 살펴봅시다
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2=arr1
arr2[0] = 100
print(arr2)

# arr2 변수를 변경하면 원래 변수(arr1)도 영향을 받고 있습니다
print(arr1)

# ndarray를 copy()를 사용해 arr2 변수에 대입한 경우를 살펴봅시다
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 =arr1.copy()
arr2[0] =100
print(arr2)

# arr2 변수를 변경해도 원래 변수(arr1)에 영향을 주지 않습니다
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]


In [49]:
# 논리값 배열로 표현 출력에 반영됨

arr = np.array([2,4,6,7])
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [50]:
# 연산결과로 논리값 배열로 표현 출력에 반영됨

arr = np.array([2,4,6,7])
print(arr[arr % 3 == 1])

[4 7]


In [51]:
# 부울 인덱스
import numpy as np

arr = np.array([2,3,4,5,6,7])

# 변수 arr의 각 요소가 2로 나누어 떨어지는지를 나타내는 부울 배열을 출력
print(arr % 2 == 0)

# 변수 arr의 각 요소 중에서 2로 나누어 떨어진 것의 배열을 출력
print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


In [39]:
# 범용함수
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

arr_abs = np.abs(arr)  #abs = 절대값
print(arr_abs)

print(np.exp(arr_abs))  # 지수함수
print(np.sqrt(arr_abs)) # 제곱근
print(np.sin(arr_abs))  
print(np.cos(arr_abs))
print(np.fix(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]
[-0.7568025   0.41211849 -0.28790332 -0.7568025   0.91294525]
[-0.65364362 -0.91113026 -0.95765948 -0.65364362  0.40808206]
[ 4.  9. 16.  4. 20.]


In [38]:
# 집합함수
import numpy as np

arr1 = [2,5,7,9,5,2]
arr2 = [2,5,8,3,1]

# 중복을 제거한 배열을 변수에 대입
new_arr1 = np.unique(arr1)
print(new_arr1)

# 합집합
print(np.union1d(new_arr1, arr2))

#교집합
print(np.intersect1d(new_arr1, arr2))

#차집합
print(np.setdiff1d(new_arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [51]:
# 난수
import numpy as np

from numpy.random import randint

arr1 = randint(0, 11, (5, 2))
print(arr1)

# 변수 arr2에 0 이상 1미만의 난수를 3개 생성
arr2 = np.random.rand(3)
print(arr2)

[[ 4  9]
 [ 0  2]
 [ 6  5]
 [ 4  4]
 [ 1 10]]
[0.02648533 0.2990319  0.25336783]


In [21]:
# 2차원배열
# 배열 각차원의 요소수를 확인 : ndarray.shape
# 지정 행렬로 변환 : ndarray.reshape(a,b)
import numpy as np

# 변수 arr에 2차원 배열을 대입하세요
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

# 변수 arr 행렬의 각 차원의 요소 수를 출력하세요
print(arr.shape)

# 변수 arr을 4행 2열의 행렬로 변환
print(arr.reshape(4,2))

arr = np.array([[1,2,3],[4,5,6]])
print(arr[1])

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[4 5 6]


In [4]:
# 인덱스 요소 반환 , 슬라이스는 :로 나머지 행,열을 표현
# 인덱스 참조와 슬라이드
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# 변수 arr의 요소 중 3을 출력하세요
print(arr[0,2])

# 변수 arr에서 부분적으로 꺼내어 출력하세요
#"1행 이후, 2열 까지"를 꺼냅니다
print(arr[1:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


In [11]:
#axis(N차원 배열을 구성하는 요소) = N차원 배열을 정의할때 사용되기도하며 여러 연산 과정에서의 기준으로도 쓰입니다.
arr = np.array([[1,2,3],[4,5,6]])

print(arr.sum())
print(arr.sum(axis=0)) # 0 세로로 계산
print(arr.sum(axis=1)) # 1 가로로 계산

21
[5 7 9]
[ 6 15]


In [10]:
import numpy as np

arr = np.array([[1,2,3],[4,5,12],[15,20,22]])  

# arr행의 합을 구하여 문제에서 제시한 1차원 배열을 반환하세요
print(arr.sum(axis=1))  # 행으로 계산 1 가로

[ 6 21 57]


In [13]:
# 팬시 인덱스 참조
arr = np.array([[1,2],[3,4],[5,6],[7,8]])  # ndarray배열 안에 []를 사용하여 인덱스번호 입력

# 3행,2행,0행을 순서대로 추출하여 새로운 요소를 만듭니다
# 인덱스 번호는 0부터 시작합니다
print(arr[[3,2,0]])

[[7 8]
 [5 6]
 [1 2]]


In [15]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 변수 arr의 행의 순서를 변경하여 출력하세요
print(arr[[1,3,0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [16]:
import numpy as np

# 1차원 배열을 생성
a = np.arange(6)
print("Original array:", a)

# 2x3 배열로 reshape
b = a.reshape((2, 3))
print("Reshaped to 2x3 array:\n", b)

Original array: [0 1 2 3 4 5]
Reshaped to 2x3 array:
 [[0 1 2]
 [3 4 5]]


In [18]:
# 전치행렬
# 행렬의 전치 : ndarray.T
# 행렬의 전치 : ndarray.transpose()
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 변수 arr을 전치하세요
print(arr.T) #print(np.transpose(arr))

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [24]:
# 정렬
# 정렬된 배열의 인덱스 : ndarray.argsort()
arr = np.array([15,30,5])
arr.argsort()

array([2, 0, 1])

In [58]:
# 정렬된 배열의 인덱스 : ndarray.argsort()
# 정렬함수 : np.sort(ndarray)
# 정렬메서드 : ndarray.sort() ; 0열단위 1행단위,
# sort = 메소드를 가지고 이 메소드는 리스트를 정렬된 상태로 변경 , 오름차순, 내림차순으로 정렬
# 반환 값은 없고(None), 함수 내에서 실행 결과가 반영되는 inplace 함수

import numpy as np

arr = np.array([[8,4,2],[3,5,1]])

# argsort() 메서드로 출력하세요
print(arr.argsort())

# np.sort() 함수로 정렬하여 출력하세요
print(np.sort(arr))

#sort() 메서드로 행을 정렬하세요
arr.sort(1)
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


In [30]:
# 행렬계산
# 행렬곱 : np.dot(a,b)
# 노름(벡터의 길이 반환) : np.linalg.norm(a)
import numpy as np

#arr을 정의합니다
arr = np.arange(9).reshape(3,3)

# 변수 arr와 arr의 행렬곱을 출력하세요
print(np.dot(arr, arr))

#vec를 정의합니다
vec = arr.reshape(9)

# 변수 vec의 노름을 출력하세요 # 벡터의 길이
print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


In [31]:
# 통계함수
#평균 : ndarray.mean(axis=0) ; 0열단위 1행단위
#합계 : ndarray.sum(axis=0) ; 0열단위 1행단위
#최솟값 : ndarray.min()
#최대값 인덱스 : ndarray.argmax(axis=0) ; 0열단위 1행단위
import numpy as np

arr = np.arange(15).reshape(3,5)

# 변수 arr의 각 열의 평균을 출력하세요
print(arr.mean(axis=0))

# 변수 arr의 행 합계를 출력하세요
print(arr.sum(axis=1))

# 변수 arr의 최소값을 출력하세요
print(arr.min())

# 변수 arr의 각 열의 최대값의 인덱스 번호를 출력하세요
print(arr.argmax(axis=0))

[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


In [36]:
# 브로드케스트
x = np.arange(6).reshape(2,3)
print(x+1)   # 배열(2*3)의 요소에 1을 각각 더함

[[1 2 3]
 [4 5 6]]


In [37]:
#배열 연산시크기가 작은배열의 행과 열을 자동으로 큰 배열쪽에 맞춤
import numpy as np

# 0에서 14사이의 정수값을 갖는 3 x 5의 ndarray 배열 x를 생성
x = np.arange(15).reshape(3,5)
print("x:")
print(x)

# 0에서 4사이의 정수값을 갖는 1 x 5의 ndarray 배열 y를 생성
y = np.array([np.arange(5)])
print("y:")
print(y)

# x의 n번째 열의 모든 행에서 n만 빼세요
z = x - y

# x를 출력
print("z:")
print(z)

x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
y:
[[0 1 2 3 4]]
z:
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
